### ISSUE TITLE
Recursive alias expansion

### ISSUE THREAD

**Issue by jtyers** [momo-lab/zsh-abbrev-alias#16]
First off, great project! Really appreciate the benefits of doing alias expansion as I type.

I make lots of use of aliases-in-aliases. For example, in my `.zshrc`:

```
abbrev-alias D='docker'
abbrev-alias Dr="D run --rm -it"
```

Here, if I type `D`, it expands correctly. However, when I type `Dr`, it only expands one level deep, i.e. `D run --rm -it`. It'd be great if the expansion happened recursively so that this became `docker run --rm -it`.

**Comment by momo-lab** [comment]
I supported recursive option(-r).
Please try it.

**Comment by jtyers** [comment]
Nice one - this works really well. Thanks :-D

**Comment by jtyers** [comment]
Could you merge to master?

**Comment by momo-lab** [comment]
Already merged.
Thank you for closing.
